### ISSUE TITLE
Change helm chart to work out of the box

### ISSUE THREAD

**Issue by zexa** [k8s-land/gitea-chart#2]
The gitea-chart does not seem to work out of the box.

Running in a minikube environmen:
```
helm repo add k8s-land https://charts.k8s.land
helm install gitea k8s-land/gitea
```

And adding gitea.local to `/etc/hosts`:
```
127.0.0.1 gitea.local
```

Seems like gitea is not accessible out of the box.
```
$ curl gitea.local
curl: (7) Failed to connect to gitea.local port 80: Connection refused
$ curl gitea.local:3000
curl: (7) Failed to connect to gitea.local port 3000: Connection refused
```

Ingress controller seems to be running:
```
$ kubectl get pods -n kube-system
NAME                                        READY   STATUS    RESTARTS   AGE
nginx-ingress-controller-7d98965d48-dq5tq   1/1     Running   1          1d
```

Please let me know if I'm missing something.

**Comment by cdrage** [comment]
Could you output `kubectl get svc` for me and let me know what the output is?

**Comment by zexa** [comment]
Seems like my problem was solved after updating minikube.
